#!/bin/bash

OUTPUT_FILE="resources.csv"

# Write header to CSV
echo "Name,Type" > $OUTPUT_FILE

# Parse Terraform state and append to CSV
terraform show -json | jq -r '.values.root_module.resources[] | select(.type | startswith("aws_")) | [.name, .type] | @csv' >> $OUTPUT_FILE

echo "Resources exported to $OUTPUT_FILE"
